{
 "title": "Counter example dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count - rate per second (per-second rate of random created names as measured over the last 1 minute)",
   "type": "timeseries",
   "description": "per-second rate of random created names as measured over the last 5 minutes, per time series in the range vector",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(random_names_created_total[1m])"
    }
   ]
  },
  {
   "title": "Count - increase per minute - (per-second rate random generated names looking up to 1 minutes)",
   "type": "timeseries",
   "description": "Function: increase (https://prometheus.io/docs/prometheus/latest/querying/functions/#increase)\n\nThe following example expression returns the per-second rate random generated names looking up to 1 minutes back for the two most recent data points, per time series in the range vector.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(random_names_created_total[1m])"
    }
   ]
  },
  {
   "title": "Counter example - total create random names",
   "type": "timeseries",
   "description": "Function: none\nMetric type: counter\nMicrometer metric: random.names.created\nPrometheus: random_names_created_total",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 16 },
   "targets": [
    { "expr": "random_names_created_total" }
   ]
  }
 ]
}